$env:PGPASSWORD = "ptSQL"
& "C:\Program Files\PostgreSQL\18\bin\psql.exe" -U postgres -c "CREATE DATABASE ""Event_Manager"";"
Write-Host "Database created!"
& "C:\Program Files\PostgreSQL\18\bin\psql.exe" -U postgres -d "Event_Manager" -f "e:\pkrfiles\events-manager\backend\databases\database.sql"
Write-Host "Schema applied!"
& "C:\Program Files\PostgreSQL\18\bin\psql.exe" -U postgres -d "Event_Manager" -f "e:\pkrfiles\events-manager\backend\databases\migration_registration.sql"
Write-Host "Registration migration applied!"
& "C:\Program Files\PostgreSQL\18\bin\psql.exe" -U postgres -d "Event_Manager" -f "e:\pkrfiles\events-manager\backend\databases\migration_trial.sql"
Write-Host "Trial migration applied!"
